name: Deploy Frontend to Azure Web App

on:
  push:
    branches: [ deploy ]
    paths:
      - "query-repair-frontend/**"
      - ".github/workflows/deploy-frontend.yml"
  workflow_dispatch:

permissions:
  contents: read

env:
  APP_DIR: query-repair-frontend
  NODE_VERSION: "20.x"   # use your App Service’s Node LTS

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: fe-deploy
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ${{ env.APP_DIR }}/package-lock.json

      - name: Install deps
        working-directory: ${{ env.APP_DIR }}
        run: npm ci

      - name: Build (bakes VITE_BACKEND_URL)
        working-directory: ${{ env.APP_DIR }}
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          CI: false
        run: npm run build

      - name: Debug baked URL (optional)
        run: grep -R "azurewebsites.net\|VITE_BACKEND_URL" -n ${{ env.APP_DIR }}/dist || true

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FE }}
          package: ${{ env.APP_DIR }}/dist
