name: Deploy FastAPI backend to Azure App Service

on:
  push:
    branches: [ deploy ]
    paths:
      - 'query-repair-backend/**'
      - 'query-repair-module/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build a deployment folder that contains BOTH backend and module
      - name: Make deploy package
        run: |
          mkdir -p package
          rsync -a --delete --exclude="__pycache__" query-repair-backend/ package/query-repair-backend/
          rsync -a --delete --exclude="__pycache__" query-repair-module/   package/query-repair-module/
          # Root requirements for Oryx on App Service
          sed 's|-e ../query-repair-module|-e ./query-repair-module|g' query-repair-backend/requirements.txt > package/requirements.txt

      # Publish directly with the Web App's publish profile secret (no azure/login)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: YOUR_APP_NAME_HERE   # e.g., qr-backend-demo
          package: package
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
