name: Deploy FastAPI backend to Azure App Service

on:
  push:
    branches: [ deploy ]
    paths:
      - 'query-repair-backend/**'
      - 'query-repair-module/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make deploy package
        run: |
          mkdir -p package
          rsync -a --delete --exclude="__pycache__" query-repair-backend/ package/query-repair-backend/
          rsync -a --delete --exclude="__pycache__" query-repair-module/   package/query-repair-module/
          # Root requirements for Oryx (editable path must be inside the zip)
          sed 's|-e ../query-repair-module|-e ./query-repair-module|g' query-repair-backend/requirements.txt > package/requirements.txt
          # Remove backend requirements so Oryx can't pick the wrong one
          rm -f package/query-repair-backend/requirements.txt

      - name: Deploy to Azure Web App (publish profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: query-repair                # <- your exact App Service name
          package: package
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
