name: Deploy Backend to Azure Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'query-repair-backend/**'
      - 'query-repair-module/**'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Deploy the entire repo so the sibling module is present on the server
      - name: Deploy to Azure Web App (Publish Profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: query-repair                # your web app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .                            # deploy repo root
