name: Deploy Backend to Azure Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'query-repair-backend/**'
      - 'query-repair-module/**'
      - 'requirements.txt'
      - 'startup.txt'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Zip the ENTIRE repo so both backend and module are included
      - name: Create deployment zip (backend + module at root)
        run: |
          zip -r deploy.zip query-repair-backend query-repair-module requirements.txt startup.txt -x "*.git*" "*/__pycache__/*"
          
      - name: Deploy to Azure Web App (Publish Profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: query-repair
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy.zip

